# Generated by Django 3.2.5 on 2021-07-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default=1, max_length=120),
        ),
        migrations.AlterField(
            model_name='question',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.concept'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.section'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.chapter'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.objective'),
        ),
    ]
