# Generated by Django 3.2.5 on 2021-07-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210726_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(default=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
