# Generated by Django 3.2.5 on 2021-07-31 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210727_1948'),
        ('quiz', '0003_auto_20210726_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='results',
            name='score',
            field=models.CharField(default='score', max_length=100),
        ),
        migrations.AddField(
            model_name='results',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
    ]
