# Generated by Django 3.2.5 on 2021-07-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0011_auto_20210726_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('count', models.SmallIntegerField()),
                ('block', models.SmallIntegerField(default=1)),
                ('level', models.SmallIntegerField(default=1)),
                ('facualty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='structure.facualty')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.programme')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField()),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.chapter')),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('objective', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.objective')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField()),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.chapter')),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('objective', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.objective')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.section')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='module.objective'),
        ),
    ]
