# Generated by Django 3.2.5 on 2021-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0012_auto_20210726_1507'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='programme',
        ),
        migrations.AddField(
            model_name='module',
            name='programmes',
            field=models.ManyToManyField(to='structure.Programme'),
        ),
    ]
