# Generated by Django 3.2.5 on 2021-08-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_auto_20210806_0147'),
        ('module', '0002_auto_20210805_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='programmes',
        ),
        migrations.AddField(
            model_name='module',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='structure.programme'),
        ),
    ]
