# Generated by Django 3.2.5 on 2021-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20210806_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='programme',
            new_name='programmes',
        ),
    ]
