# Generated by Django 3.2.5 on 2021-08-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_rename_programme_module_programmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='programmes',
        ),
    ]
