# Generated by Django 3.2.5 on 2021-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_teacher_module'),
        ('module', '0005_remove_module_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(to='users.Teacher'),
        ),
    ]
